#pragma once

#include "Pos.hpp"

void Pos::init_config_ticket(){
    std::string xml ="<interface>"
 "<object class='GtkWindow' id='window_conf_ticket'>"
   "<property name='default-height'>400</property>"
   "<property name='title'>Configuracion de Tickets.</property>"
   "<child>"
     "<object class='GtkBox'>"
       "<child>"
         "<object class='GtkScrolledWindow'>"
           "<property name='hexpand'>0</property>"
           "<property name='hscrollbar-policy'>never</property>"
           "<property name='min-content-height'>200</property>"
           "<property name='vexpand'>1</property>"
           "<child>"
             "<object class='GtkViewport'>"
               "<property name='scroll-to-focus'>1</property>"
               "<child>"
                 "<object class='GtkBox'>"
                   "<property name='margin-bottom'>30</property>"
                   "<property name='margin-end'>60</property>"
                   "<property name='margin-start'>60</property>"
                   "<property name='margin-top'>30</property>"
                   "<property name='orientation'>vertical</property>"
                   "<child>"
                     "<object class='GtkLabel'>"
                       "<property name='label'>Visualización</property>"
                       "<property name='margin-bottom'>10</property>"
                       "<property name='xalign'>0</property>"
                       "<style>"
                         "<class name='title-2'/>"
                       "</style>"
                     "</object>"
                   "</child>"
                   "<child>"
                     "<object class='GtkListBox'>"
                       "<property name='selection-mode'>none</property>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='switch_label'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Mensaje de Agradecimiento</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkCheckButton' id='check_6'>"
                                   "<property name='active'>1</property>"
                                   "<property name='halign'>end</property>"
                                   "<property name='margin-end'>10</property>"
                                   "<property name='margin-start'>10</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='check_label'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Fecha</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkCheckButton' id='check'>"
                                   "<property name='active'>1</property>"
                                   "<property name='halign'>end</property>"
                                   "<property name='margin-end'>10</property>"
                                   "<property name='margin-start'>10</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='check_label_2'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Direccion</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkCheckButton' id='check_2'>"
                                   "<property name='active'>1</property>"
                                   "<property name='halign'>end</property>"
                                   "<property name='margin-end'>10</property>"
                                   "<property name='margin-start'>10</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='check_label_3'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>RFC</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkCheckButton' id='check_3'>"
                                   "<property name='active'>1</property>"
                                   "<property name='halign'>end</property>"
                                   "<property name='margin-end'>10</property>"
                                   "<property name='margin-start'>10</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='check_label_4'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Vendedor</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkCheckButton' id='check_4'>"
                                   "<property name='active'>1</property>"
                                   "<property name='halign'>end</property>"
                                   "<property name='margin-end'>10</property>"
                                   "<property name='margin-start'>10</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='check_label_5'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Contacto</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkCheckButton' id='check_5'>"
                                   "<property name='active'>1</property>"
                                   "<property name='halign'>end</property>"
                                   "<property name='margin-end'>10</property>"
                                   "<property name='margin-start'>10</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<style>"
                         "<class name='rich-list'/>"
                         "<class name='boxed-list'/>"
                       "</style>"
                     "</object>"
                   "</child>"
                   "<child>"
                     "<object class='GtkLabel'>"
                       "<property name='label'>Datos</property>"
                       "<property name='margin-bottom'>10</property>"
                       "<property name='margin-top'>30</property>"
                       "<property name='xalign'>0</property>"
                       "<style>"
                         "<class name='title-2'/>"
                       "</style>"
                     "</object>"
                   "</child>"
                   "<child>"
                     "<object class='GtkListBox'>"
                       "<property name='selection-mode'>none</property>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<property name='activatable'>0</property>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='entry_label_3'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Direccion</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkEntry'>"
                                   "<property name='halign'>end</property>"
                                   "<property name='placeholder-text'>Type here…</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<property name='activatable'>0</property>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='entry_label'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>RFC</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkEntry'>"
                                   "<property name='halign'>end</property>"
                                   "<property name='placeholder-text'>Type here…</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<property name='activatable'>0</property>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='entry_label_4'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Contacto</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkEntry'>"
                                   "<property name='halign'>end</property>"
                                   "<property name='placeholder-text'>Type here…</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<child>"
                         "<object class='GtkListBoxRow'>"
                           "<property name='activatable'>0</property>"
                           "<child>"
                             "<object class='GtkBox'>"
                               "<child>"
                                 "<object class='GtkLabel' id='entry_label_5'>"
                                   "<property name='halign'>start</property>"
                                   "<property name='hexpand'>1</property>"
                                   "<property name='label'>Agradecimiento</property>"
                                   "<property name='valign'>center</property>"
                                   "<property name='xalign'>0</property>"
                                 "</object>"
                               "</child>"
                               "<child>"
                                 "<object class='GtkEntry'>"
                                   "<property name='halign'>end</property>"
                                   "<property name='placeholder-text'>Type here…</property>"
                                   "<property name='valign'>center</property>"
                                 "</object>"
                               "</child>"
                             "</object>"
                           "</child>"
                         "</object>"
                       "</child>"
                       "<style>"
                         "<class name='rich-list'/>"
                         "<class name='boxed-list'/>"
                       "</style>"
                     "</object>"
                   "</child>"
                 "</object>"
               "</child>"
             "</object>"
           "</child>"
         "</object>"
       "</child>"
       "<child>"
         "<object class='GtkScrolledWindow'>"
           "<property name='hexpand'>True</property>"
           "<property name='margin-bottom'>20</property>"
           "<property name='margin-end'>10</property>"
           "<property name='margin-start'>30</property>"
           "<property name='margin-top'>20</property>"
           "<child>"
             "<object class='GtkTextView'>"
               "<property name='editable'>False</property>"
               "<property name='monospace'>True</property>"
             "</object>"
           "</child>"
         "</object>"
       "</child>"
     "</object>"
   "</child>"
 "</object>"
 "<object class='GtkSizeGroup'>"
   "<property name='mode'>horizontal</property>"
   "<widgets>"
     "<widget name='switch_label'/>"
     "<widget name='check_label'/>"
     "<widget name='entry_label'/>"
   "</widgets>"
 "</object>"
"</interface>";

    auto  builder_config_ticket_ = Gtk::Builder::create();
    try
  {
    builder_config_ticket_->add_from_string(xml);
  }catch(const Glib::Error& ex)
  {
    std::cerr << "building toolbar failed: " << ex.what();
  } 
    window_conf_ticket = builder_config_ticket_->get_widget<Gtk::Window>("window_conf_ticket");
    window_conf_ticket->set_transient_for(*this);
    window_conf_ticket->set_modal(true);
    window_conf_ticket->set_hide_on_close(true);
    window_conf_ticket->set_default_size(700, 500);
}